### ISSUE TITLE
リリースしませんか

### ISSUE THREAD

**Issue by k-okada** [longjie/longjie_ros_pkg#1]
素晴らしいです
せっかくなのでdebリリースしませんか？
Cc:@garaemon, @130s

**Comment by longjie** [comment]
すいません、帰省行脚で今日から復帰です。もうわかってるかもしれませんが、

* https://github.com/ps4eye/ps4eye はps4eye_init.pyだけ使っていて、たぶん関連のpythonとbinだけあれば使えます。ただし、カメラを挿すたびにやる必要があります。できればパッケージに含めるほうが便利だとは思いますが、いいのかな。
* ちょうど今日、もともとの https://github.com/ps4eye/ps4eye のメインの人からメールが来ました。現在はこっちに注力しているそうです。https://github.com/bigboss-ps3dev/PS4EYECam
* カメラキャリブは必須で、ROSのcamera_calibrationでやりました。
* パラメータファイルの変更ありがとうございました。

今後は https://github.com/longjie/ps4eye のほうでやったほうがいいかと思います。この longjie_ros_pkgは再利用しにくいことがわかったので放棄して、今後はパッケージごとにレポジトリを作るようにします。

**Comment by k-okada** [comment]
２ヶ月以上かかりましたが，ようやく陽の目を見ましたね！．http://lists.ros.org/pipermail/ros-users/2015-February/069166.html

**Comment by k-okada** [comment]
ところで，
http://wiki.ros.org/ps4eye/
がまだ無いですが，
https://github.com/ros/rosdistro/blob/master/hydro/distribution.yaml#L5887
が有るんだけど，これを書いたからって，wikiは出来ないんでしたっけ？
自分でPackageTepmlateポチって作っていいんでしたっけ？ > @130s

**Comment by 130s** [comment]
そうです．

今やっておきました．http://wiki.ros.org/ps4eye 生成されてますね!

**Comment by k-okada** [comment]
ありがとうございます．youtube，貼っておきました．

**Comment by longjie** [comment]
wow, ありがとうございます。
使う人どのくらいいるかな。

**Comment by 130s** [comment]
告知・SEO (つまりドキュメント充実) が大事っぽいです．とりあえず TORK で retweet しておきました．
